[workspace]
resolver = "2"
members = [
    "crates/*",
    "crates/bin/slot-setter",
    "crates/bin/dnsd",
    "cmd/*"
]
exclude = [
    "crates/bin"
]

[workspace.dependencies]
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
thiserror = "1"
metrics = "0.24"
metrics-exporter-prometheus = "0.12"
metrics-exporter-opentelemetry = "0.1"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
bb8 = "0.9"
redis = { version = "0.32", default-features = false, features = ["tokio-comp"] }
rustls = "0.23"
tokio-rustls = "0.26"
rand = "0.8"
clap = { version = "4", features = ["derive"] }
rustls-pemfile = "1"

