apiVersion: v1
kind: Service
metadata:
  name: mimir
  namespace: fleetingdns
  labels:
    app: mimir
    component: observability
spec:
  type: ClusterIP
  ports:
    - port: 9009
      targetPort: 9009
      protocol: TCP
      name: http
    - port: 9095
      targetPort: 9095
      protocol: TCP
      name: grpc
  selector:
    app: mimir 