apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-gcp
  namespace: crossplane-system
spec:
  package: xpkg.upbound.io/upbound/provider-gcp:v0.42.0
  runtimeConfigRef:
    name: provider-gcp-runtime-config
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: provider-gcp-runtime-config
  namespace: crossplane-system
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          serviceAccountName: crossplane-provider-gcp
          containers:
          - name: package-runtime
            resources:
              requests:
                memory: "512Mi"
                cpu: "250m"
              limits:
                memory: "1Gi"
                cpu: "500m"
            env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
            volumeMounts:
            - name: gcp-credentials
              mountPath: /var/secrets/google
              readOnly: true
          volumes:
          - name: gcp-credentials
            secret:
              secretName: gcp-credentials
              items:
              - key: credentials
                path: key.json
---
apiVersion: gcp.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  projectID: fleetingdns-infra
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: gcp-credentials
      key: credentials
---
apiVersion: gcp.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: analytics
spec:
  projectID: fleetingdns-analytics
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: gcp-credentials
      key: credentials
---
apiVersion: gcp.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: security
spec:
  projectID: fleetingdns-security
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: gcp-credentials
      key: credentials 