apiVersion: v1
kind: Service
metadata:
  name: edgehub
  namespace: fleetingdns
  labels:
    app: edgehub
    component: core
spec:
  type: ClusterIP
  ports:
    - port: 2222
      targetPort: 2222
      protocol: TCP
      name: tunnel
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: metrics
  selector:
    app: edgehub 