apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: fleetingdns-autopilot-clusters
  annotations:
    config.kubernetes.io/local-config: "true"

resources:
- workload-clusters.yaml

commonLabels:
  app.kubernetes.io/name: fleetingdns-autopilot-clusters
  app.kubernetes.io/component: k8s-cluster
  app.kubernetes.io/part-of: fleetingdns
  app.kubernetes.io/managed-by: crossplane
  cluster-type: autopilot

patches:
- target:
    group: "*"
    version: "*"
    kind: "*"
  patch: |-
    - op: add
      path: /metadata/annotations/crossplane.io~1managed-by
      value: fleetingdns-platform
    - op: add
      path: /metadata/annotations/fleetingdns.io~1cluster-type
      value: autopilot-workload 