apiVersion: compute.gcp.upbound.io/v1beta1
kind: NetworkPeering
metadata:
  name: infra-to-analytics-peering
  labels:
    app.kubernetes.io/name: infra-to-analytics-peering
    app.kubernetes.io/component: networking
    app.kubernetes.io/part-of: fleetingdns-infrastructure
    fleetingdns.com/environment: infrastructure
    fleetingdns.com/region: global
spec:
  forProvider:
    name: infra-to-analytics-peering
    networkRef:
      name: fleetingdns-infra-vpc
    peerNetwork: "projects/fleetingdns-analytics/global/networks/fleetingdns-analytics-vpc"
    autoCreateRoutes: true
    importCustomRoutes: true
    exportCustomRoutes: true
  providerConfigRef:
    name: gcp-provider-config-infra
---
apiVersion: compute.gcp.upbound.io/v1beta1
kind: NetworkPeering
metadata:
  name: analytics-to-infra-peering
  labels:
    app.kubernetes.io/name: analytics-to-infra-peering
    app.kubernetes.io/component: networking
    app.kubernetes.io/part-of: fleetingdns-infrastructure
    fleetingdns.com/environment: analytics
    fleetingdns.com/region: global
spec:
  forProvider:
    name: analytics-to-infra-peering
    networkRef:
      name: fleetingdns-analytics-vpc
    peerNetwork: "projects/fleetingdns-infra/global/networks/fleetingdns-infra-vpc"
    autoCreateRoutes: true
    importCustomRoutes: true
    exportCustomRoutes: true
  providerConfigRef:
    name: gcp-provider-config-analytics 