apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Flux v2.6.2 installation
  - versions/v2_6_2/
  
  # Flux GitRepository and Kustomization sync resources
  - sync/

namespace: flux-system

commonLabels:
  app.kubernetes.io/part-of: flux-system
  app.kubernetes.io/managed-by: kustomize

# The flux-system namespace is created by the Flux installation 