- op: replace
  path: /spec/type
  value: LoadBalancer
- op: add
  path: /metadata/annotations
  value:
    cloud.google.com/load-balancer-type: "External"
    networking.gke.io/load-balancer-type: "External" 