apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  
  # Infrastructure components
  - ../components/redis/
  - ../components/postgresql/
  
  # FleetingDNS services
  - ../fleetingdns/dnsd/
  - ../fleetingdns/edgehub/
  - ../fleetingdns/api/ 