apiVersion: cloudresourcemanager.gcp.crossplane.io/v1alpha1
kind: Folder
metadata:
  name: fleetingdns-environments-folder
  labels:
    app.kubernetes.io/name: fleetingdns-environments
    app.kubernetes.io/component: organization
    app.kubernetes.io/part-of: fleetingdns-infrastructure
  annotations:
    crossplane.io/external-name: fleetingdns-environments
spec:
  forProvider:
    displayName: "Environments"
    parentRef:
      name: fleetingdns-folder
  providerConfigRef:
    name: gcp-provider-config
  writeConnectionSecretsToRef:
    namespace: crossplane-system 