[package]
name = "edgehub"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
common = { path = "../common" }
rustls = { workspace = true }
tokio-rustls = { workspace = true }
rand = { workspace = true }
dnsd = { path = "../dnsd" }
redis = { workspace = true }

[features]
e2e = []

[dev-dependencies]
tracing-test = "0.2"
rustls-pemfile = { workspace = true }
mini-redis = "0.4"
hickory-resolver = "0.24"
